/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import datos.Deporte;
import gui.tablemodels.DeporteTableModel;
import gui.tablemodels.SocioTableModel;
import logicaNegocio.logicaNegocioSocio;
/**
 *
 * @author Jhony
 */
public class Deportes extends javax.swing.JFrame {

    private logicaNegocioSocio logica;
    
    /**
     * Creates new form Deportes
     */
    public Deportes(logicaNegocioSocio logica) {
        initComponents();
        this.logica = logica;
        setModeloTabla();
    }
    
    public void setModeloTabla() {
        DeporteTableModel tablaSocios = new DeporteTableModel(logica.getDeportes());
        jTableDeportes.setModel(tablaSocios);
        tablaSocios.fireTableDataChanged();
    }
    
    public void addVariosDeportes () {
        Deporte socio1 = new Deporte("1", "jhony", 22);
        Deporte socio2 = new Deporte("2", "jhony", 22);
        Deporte socio3 = new Deporte("3", "jhony", 22);
        Deporte socio4 = new Deporte("4", "jhony", 22);

        
        logica.addDeporte(socio4);
        logica.addDeporte(socio2);
        logica.addDeporte(socio1);
        logica.addDeporte(socio3);   
        
        setModeloTabla();
    }

    public void addSocio(Deporte d) {
        logica.addDeporte(d);
        setModeloTabla();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAddSocio = new javax.swing.JButton();
        jButtonModificarSocio1 = new javax.swing.JButton();
        jButtonModificarSocio = new javax.swing.JButton();
        jButtonDeleteSocio = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDeportes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAddSocio.setText("Añadir");
        jButtonAddSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSocioActionPerformed(evt);
            }
        });

        jButtonModificarSocio1.setText("Gestionar Socios");
        jButtonModificarSocio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarSocio1ActionPerformed(evt);
            }
        });

        jButtonModificarSocio.setText("Modificar");
        jButtonModificarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarSocioActionPerformed(evt);
            }
        });

        jButtonDeleteSocio.setText("Borrar");
        jButtonDeleteSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteSocioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 48)); // NOI18N
        jLabel1.setText("Deportes");

        jTableDeportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.", "Descripción", "Niveles"
            }
        ));
        jScrollPane1.setViewportView(jTableDeportes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAddSocio)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModificarSocio)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteSocio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModificarSocio1))
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(323, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddSocio)
                    .addComponent(jButtonModificarSocio)
                    .addComponent(jButtonDeleteSocio)
                    .addComponent(jButtonModificarSocio1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSocioActionPerformed
        AddDeporte deporte = new AddDeporte(this, true);
        deporte.setModificar(false);
        deporte.setVisible(true);
    }//GEN-LAST:event_jButtonAddSocioActionPerformed

    private void jButtonModificarSocio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarSocio1ActionPerformed
        Socios socios = new Socios(logica);
        socios.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButtonModificarSocio1ActionPerformed

    private void jButtonModificarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarSocioActionPerformed
        int fila = jTableDeportes.getSelectedRow();

        Deporte deporteSeleccionado = logicaApp.obtenerDeportes().get(fila);

        AddDeporte deporteDialog = new AddDeporte(this, true);
        deporteDialog.setModificar(true);
        deporteDialog.setTextDeportes(deporteSeleccionado);
        deporteDialog.setVisible(true);

    }//GEN-LAST:event_jButtonModificarSocioActionPerformed

    private void jButtonDeleteSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteSocioActionPerformed
        int fila = jTableDeportes.getSelectedRow();

        Deporte deporte = logicaApp.obtenerDeportes().get(fila);

        logicaApp.obtenerDeportes().remove(deporte);

        setModeloTabla();
    }//GEN-LAST:event_jButtonDeleteSocioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddSocio;
    private javax.swing.JButton jButtonDeleteSocio;
    private javax.swing.JButton jButtonModificarSocio;
    private javax.swing.JButton jButtonModificarSocio1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableDeportes;
    // End of variables declaration//GEN-END:variables
}
