/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio10;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Jh0ny2k2
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelDesktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jCheckBoxMezcladora = new javax.swing.JCheckBox();
        jCheckBoxRegistro = new javax.swing.JCheckBox();
        jCheckBoxMinisterio = new javax.swing.JCheckBox();
        jCheckBoxImitador = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelDesktopLayout = new javax.swing.GroupLayout(panelDesktop);
        panelDesktop.setLayout(panelDesktopLayout);
        panelDesktopLayout.setHorizontalGroup(
            panelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1459, Short.MAX_VALUE)
        );
        panelDesktopLayout.setVerticalGroup(
            panelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("TODOS PARA UNO, UNO PARA TODOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Apellidos:");

        jTextFieldApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidosActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBoxMezcladora);
        jCheckBoxMezcladora.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBoxMezcladora.setText("Mezcladora de Nombres");
        jCheckBoxMezcladora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMezcladoraActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBoxRegistro);
        jCheckBoxRegistro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBoxRegistro.setText("Registro Deportivo");
        jCheckBoxRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxRegistroActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBoxMinisterio);
        jCheckBoxMinisterio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBoxMinisterio.setText("App Ministerio");
        jCheckBoxMinisterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMinisterioActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBoxImitador);
        jCheckBoxImitador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBoxImitador.setText("Imitador");
        jCheckBoxImitador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxImitadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombre)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jCheckBoxMinisterio))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jCheckBoxRegistro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jCheckBoxImitador))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jCheckBoxMezcladora)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(panelDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(jCheckBoxMezcladora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxRegistro)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxImitador)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxMinisterio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidosActionPerformed

    private void jCheckBoxImitadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxImitadorActionPerformed
        String nombre = jTextFieldNombre.getText();
        String apellidos = jTextFieldApellidos.getText();
        if (nombre.isEmpty() || apellidos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese su nombre y apellidos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ImitadorInternal imitador = new ImitadorInternal();
        imitador.setTitle(nombre + " " + apellidos + ": Imitador");
        panelDesktop.add(imitador);
        imitador.setVisible(true);
    }//GEN-LAST:event_jCheckBoxImitadorActionPerformed

    private void jCheckBoxRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRegistroActionPerformed
        String nombre = jTextFieldNombre.getText();
        String apellidos = jTextFieldApellidos.getText();

        if (nombre.isEmpty() || apellidos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese su nombre y apellidos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        InicioRegistro registro = new InicioRegistro(this.panelDesktop);
        registro.setTitle(nombre + " " + apellidos + ": Registro Deportivo");
        panelDesktop.add(registro);
        registro.setVisible(true);

    }//GEN-LAST:event_jCheckBoxRegistroActionPerformed

    private void jCheckBoxMinisterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMinisterioActionPerformed
        String nombre = jTextFieldNombre.getText();
        String apellidos = jTextFieldApellidos.getText();
        if (nombre.isEmpty() || apellidos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese su nombre y apellidos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        AppMinisterio ministerioApp = new AppMinisterio(this.panelDesktop);
        ministerioApp.setTitle(nombre + " " + apellidos + ": App Ministerio");
        panelDesktop.add(ministerioApp);
        ministerioApp.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMinisterioActionPerformed

    private void jCheckBoxMezcladoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMezcladoraActionPerformed
        String nombre = jTextFieldNombre.getText();
        String apellidos = jTextFieldApellidos.getText();

        if (nombre.isEmpty() || apellidos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese su nombre y apellidos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Mezcladora mezcladora = new Mezcladora();
        mezcladora.setTitle(nombre + " " + apellidos + ": Mezcladora de Nombres");
        panelDesktop.add(mezcladora);
        mezcladora.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMezcladoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBoxImitador;
    private javax.swing.JCheckBox jCheckBoxMezcladora;
    private javax.swing.JCheckBox jCheckBoxMinisterio;
    private javax.swing.JCheckBox jCheckBoxRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JDesktopPane panelDesktop;
    // End of variables declaration//GEN-END:variables
}
