/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import datos.Deporte;
import datos.Socio;
import gui.tablemodels.ModeloTableDeportes;
import gui.tablemodels.ModeloTableSocios;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Jh0ny2k2
 */
public class Deportes extends javax.swing.JFrame {
    
    private ArrayList<Deporte> deportes = new ArrayList<>();
    /**
     * Creates new form Socios
     */
    public Deportes() {
        initComponents();
        inicializarTabla();
        setModeloTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonModificarSocio = new javax.swing.JButton();
        jButtonDeleteSocio = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDeportes = new javax.swing.JTable();
        jButtonAddSocio = new javax.swing.JButton();
        jButtonModificarSocio1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonModificarSocio.setText("Modificar");
        jButtonModificarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarSocioActionPerformed(evt);
            }
        });

        jButtonDeleteSocio.setText("Borrar");
        jButtonDeleteSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteSocioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 48)); // NOI18N
        jLabel1.setText("Deportes");

        jTableDeportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.", "Descripción", "Niveles"
            }
        ));
        jScrollPane1.setViewportView(jTableDeportes);

        jButtonAddSocio.setText("Añadir");
        jButtonAddSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSocioActionPerformed(evt);
            }
        });

        jButtonModificarSocio1.setText("Gestionar Socios");
        jButtonModificarSocio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarSocio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAddSocio)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModificarSocio)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteSocio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModificarSocio1))
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(338, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddSocio)
                    .addComponent(jButtonModificarSocio)
                    .addComponent(jButtonDeleteSocio)
                    .addComponent(jButtonModificarSocio1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<Deporte> obtenerDeportes() { 
        return deportes;    
    }
    
    public void addDeporte(Deporte d) {
        deportes.add(d);
        setModeloTabla(); 
    }
    
    private void setModeloTabla() {
        ModeloTableDeportes tablaDeportes = new ModeloTableDeportes(obtenerDeportes());
        jTableDeportes.setModel(tablaDeportes);
        tablaDeportes.fireTableDataChanged();
    }
    
    private void jButtonAddSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSocioActionPerformed
        AddDeporte deporte = new AddDeporte(this, true, this);
        deporte.setVisible(true);
    }//GEN-LAST:event_jButtonAddSocioActionPerformed

    private void jButtonDeleteSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteSocioActionPerformed
        int fila = jTableDeportes.getSelectedRow();
        
        Deporte deporte = obtenerDeportes().get(fila);
        
        obtenerDeportes().remove(deporte);
        
        setModeloTabla();
    }//GEN-LAST:event_jButtonDeleteSocioActionPerformed

    private void jButtonModificarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarSocioActionPerformed
        int fila = jTableDeportes.getSelectedRow();
        
        Deporte deporteSeleccionado = obtenerDeportes().get(fila);
        
        
        
        AddDeporte deporte = new AddDeporte(this, true, this);
        deporte.setTextDeportes(deporteSeleccionado);
        deporte.setVisible(true);
    }//GEN-LAST:event_jButtonModificarSocioActionPerformed

    private void jButtonModificarSocio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarSocio1ActionPerformed
        Socios socios = new Socios();
        socios.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonModificarSocio1ActionPerformed

    private void inicializarTabla() {
        ModeloTableDeportes modelo = new ModeloTableDeportes(obtenerDeportes());
        jTableDeportes.setModel(modelo);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddSocio;
    private javax.swing.JButton jButtonDeleteSocio;
    private javax.swing.JButton jButtonModificarSocio;
    private javax.swing.JButton jButtonModificarSocio1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableDeportes;
    // End of variables declaration//GEN-END:variables
}
