/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ejercicio10;

/**
 *
 * @author Jh0ny2k2
 */
public class ImitadorInternal extends javax.swing.JInternalFrame {

    /**
     * Creates new form ImitadorInternal
     */
    public ImitadorInternal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonInicio = new javax.swing.JButton();
        jTextFieldOriginal = new javax.swing.JTextField();
        jRadioButtonOpcion2 = new javax.swing.JRadioButton();
        jComboBoxOriginal = new javax.swing.JComboBox<>();
        jCheckBoxOpcion5 = new javax.swing.JCheckBox();
        jspinner = new javax.swing.JSpinner();
        jRadioButtonOpcion1 = new javax.swing.JRadioButton();
        jCheckBoxOpcion4 = new javax.swing.JCheckBox();
        jCheckBoxOpcion6 = new javax.swing.JCheckBox();
        jRadioButtonOpcion3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonEspejoOpcion1 = new javax.swing.JRadioButton();
        jRadioButtonEspejoOpcion2 = new javax.swing.JRadioButton();
        jRadioButtonEspejoOpcion3 = new javax.swing.JRadioButton();
        jCheckBoxEspejoOpcion6 = new javax.swing.JCheckBox();
        jCheckBoxEspejoOpcion5 = new javax.swing.JCheckBox();
        jCheckBoxEspejoOpcion4 = new javax.swing.JCheckBox();
        jTextFieldEspejo = new javax.swing.JTextField();
        jComboBoxEspejo = new javax.swing.JComboBox<>();
        jSpinnerEspiner = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonInicio1 = new javax.swing.JButton();

        jButtonInicio.setText("Menú Principal");
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });

        jTextFieldOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOriginalActionPerformed(evt);
            }
        });

        jRadioButtonOpcion2.setText("Opción 2");
        jRadioButtonOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOpcion2ActionPerformed(evt);
            }
        });

        jComboBoxOriginal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOriginalActionPerformed(evt);
            }
        });

        jCheckBoxOpcion5.setText("Opción 5");
        jCheckBoxOpcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOpcion5ActionPerformed(evt);
            }
        });

        jspinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspinnerStateChanged(evt);
            }
        });

        jRadioButtonOpcion1.setText("Opción 1");
        jRadioButtonOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOpcion1ActionPerformed(evt);
            }
        });

        jCheckBoxOpcion4.setText("Opción 4");
        jCheckBoxOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOpcion4ActionPerformed(evt);
            }
        });

        jCheckBoxOpcion6.setText("Opción 6");
        jCheckBoxOpcion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOpcion6ActionPerformed(evt);
            }
        });

        jRadioButtonOpcion3.setText("Opción 3");
        jRadioButtonOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOpcion3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Original");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Espejo");

        jRadioButtonEspejoOpcion1.setText("Opción 1");
        jRadioButtonEspejoOpcion1.setEnabled(false);

        jRadioButtonEspejoOpcion2.setText("Opción 2");
        jRadioButtonEspejoOpcion2.setEnabled(false);

        jRadioButtonEspejoOpcion3.setText("Opción 3");
        jRadioButtonEspejoOpcion3.setEnabled(false);

        jCheckBoxEspejoOpcion6.setText("Opción 6");
        jCheckBoxEspejoOpcion6.setEnabled(false);

        jCheckBoxEspejoOpcion5.setText("Opción 5");
        jCheckBoxEspejoOpcion5.setEnabled(false);
        jCheckBoxEspejoOpcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEspejoOpcion5ActionPerformed(evt);
            }
        });

        jCheckBoxEspejoOpcion4.setText("Opción 4");
        jCheckBoxEspejoOpcion4.setEnabled(false);

        jTextFieldEspejo.setEnabled(false);

        jComboBoxEspejo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEspejo.setEnabled(false);

        jSpinnerEspiner.setEnabled(false);

        jButtonInicio1.setText("Menú Principal");
        jButtonInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonOpcion1)
                                    .addComponent(jRadioButtonOpcion2)
                                    .addComponent(jRadioButtonOpcion3))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxOpcion4)
                                    .addComponent(jCheckBoxOpcion5)
                                    .addComponent(jCheckBoxOpcion6))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldOriginal)
                                    .addComponent(jComboBoxOriginal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jspinner, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonEspejoOpcion1)
                                    .addComponent(jRadioButtonEspejoOpcion2)
                                    .addComponent(jRadioButtonEspejoOpcion3))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxEspejoOpcion4)
                                    .addComponent(jCheckBoxEspejoOpcion5)
                                    .addComponent(jCheckBoxEspejoOpcion6))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldEspejo)
                                    .addComponent(jComboBoxEspejo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSpinnerEspiner, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonInicio1)
                                    .addComponent(jLabel1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jButtonInicio1)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonOpcion1)
                    .addComponent(jCheckBoxOpcion4)
                    .addComponent(jTextFieldOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonOpcion2)
                    .addComponent(jCheckBoxOpcion5)
                    .addComponent(jComboBoxOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonOpcion3)
                    .addComponent(jCheckBoxOpcion6)
                    .addComponent(jspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonEspejoOpcion1)
                    .addComponent(jCheckBoxEspejoOpcion4)
                    .addComponent(jTextFieldEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonEspejoOpcion2)
                    .addComponent(jCheckBoxEspejoOpcion5)
                    .addComponent(jComboBoxEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonEspejoOpcion3)
                    .addComponent(jCheckBoxEspejoOpcion6)
                    .addComponent(jSpinnerEspiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOriginalActionPerformed
        String comentario = jTextFieldOriginal.getText();

        jTextFieldEspejo.setText(comentario);
    }//GEN-LAST:event_jTextFieldOriginalActionPerformed

    private void jRadioButtonOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOpcion2ActionPerformed
        if ( jRadioButtonOpcion2.isSelected()) {
            jRadioButtonEspejoOpcion2.setSelected(true);
        } else if (!jRadioButtonOpcion2.isSelected()) {
            jRadioButtonEspejoOpcion2.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonOpcion2ActionPerformed

    private void jComboBoxOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOriginalActionPerformed
        if (jComboBoxOriginal.getSelectedItem() == "Item 1") {
            jComboBoxEspejo.setSelectedItem("Item 1");
        } else if (jComboBoxOriginal.getSelectedItem() == "Item 2") {
            jComboBoxEspejo.setSelectedItem("Item 2");
        } else if (jComboBoxOriginal.getSelectedItem() == "Item 3") {
            jComboBoxEspejo.setSelectedItem("Item 3");
        } else if (jComboBoxOriginal.getSelectedItem() == "Item 4") {
            jComboBoxEspejo.setSelectedItem("Item 4");
        }
    }//GEN-LAST:event_jComboBoxOriginalActionPerformed

    private void jCheckBoxOpcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxOpcion5ActionPerformed
        if ( jCheckBoxOpcion5.isSelected()) {
            jCheckBoxEspejoOpcion5.setSelected(true);
        } else if (!jCheckBoxOpcion5.isSelected()) {
            jCheckBoxEspejoOpcion5.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBoxOpcion5ActionPerformed

    private void jspinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspinnerStateChanged
        Object value = jspinner.getValue();

        jSpinnerEspiner.setValue(value);
    }//GEN-LAST:event_jspinnerStateChanged

    private void jRadioButtonOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOpcion1ActionPerformed
        if ( jRadioButtonOpcion1.isSelected()) {
            jRadioButtonEspejoOpcion1.setSelected(true);
        } else if (!jRadioButtonOpcion1.isSelected()) {
            jRadioButtonEspejoOpcion1.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonOpcion1ActionPerformed

    private void jCheckBoxOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxOpcion4ActionPerformed
        if ( jCheckBoxOpcion4.isSelected()) {
            jCheckBoxEspejoOpcion4.setSelected(true);
        } else if (!jCheckBoxOpcion4.isSelected()) {
            jCheckBoxEspejoOpcion4.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBoxOpcion4ActionPerformed

    private void jCheckBoxOpcion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxOpcion6ActionPerformed
        if ( jCheckBoxOpcion6.isSelected()) {
            jCheckBoxEspejoOpcion6.setSelected(true);
        } else if (!jCheckBoxOpcion6.isSelected()) {
            jCheckBoxEspejoOpcion6.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBoxOpcion6ActionPerformed

    private void jRadioButtonOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOpcion3ActionPerformed
        if ( jRadioButtonOpcion3.isSelected()) {
            jRadioButtonEspejoOpcion3.setSelected(true);
        } else if (!jRadioButtonOpcion3.isSelected()) {
            jRadioButtonEspejoOpcion3.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonOpcion3ActionPerformed

    private void jCheckBoxEspejoOpcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEspejoOpcion5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEspejoOpcion5ActionPerformed

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonInicioActionPerformed

    private void jButtonInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicio1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonInicio1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JButton jButtonInicio1;
    private javax.swing.JCheckBox jCheckBoxEspejoOpcion4;
    private javax.swing.JCheckBox jCheckBoxEspejoOpcion5;
    private javax.swing.JCheckBox jCheckBoxEspejoOpcion6;
    private javax.swing.JCheckBox jCheckBoxOpcion4;
    private javax.swing.JCheckBox jCheckBoxOpcion5;
    private javax.swing.JCheckBox jCheckBoxOpcion6;
    private javax.swing.JComboBox<String> jComboBoxEspejo;
    private javax.swing.JComboBox<String> jComboBoxOriginal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButtonEspejoOpcion1;
    private javax.swing.JRadioButton jRadioButtonEspejoOpcion2;
    private javax.swing.JRadioButton jRadioButtonEspejoOpcion3;
    private javax.swing.JRadioButton jRadioButtonOpcion1;
    private javax.swing.JRadioButton jRadioButtonOpcion2;
    private javax.swing.JRadioButton jRadioButtonOpcion3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerEspiner;
    private javax.swing.JTextField jTextFieldEspejo;
    private javax.swing.JTextField jTextFieldOriginal;
    private javax.swing.JSpinner jspinner;
    // End of variables declaration//GEN-END:variables
}
