/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ejercicio10;

import java.awt.Component;
import java.awt.PopupMenu;

/**
 *
 * @author Jh0ny2k2
 */
public class Mezcladora extends javax.swing.JInternalFrame {

    /**
     * Creates new form Mezcladora
     */
    public Mezcladora() {
        initComponents();
        jButtonReiniciar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelResultado = new javax.swing.JLabel();
        jButtonReiniciar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonMezclar = new javax.swing.JButton();
        jTextFieldSegundoNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPrimerNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonInicio = new javax.swing.JButton();

        jButtonReiniciar.setText("REINICIAR");
        jButtonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReiniciarActionPerformed(evt);
            }
        });

        jLabel4.setText("Estos son posibles nombres mezclados:");

        jButtonMezclar.setText("MEZCLAR");
        jButtonMezclar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMezclarActionPerformed(evt);
            }
        });

        jLabel3.setText("Segundo Nombre:");

        jTextFieldPrimerNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrimerNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Primer Nombre:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Mezcladora de Nombres");

        jButtonInicio.setText("Menú Principal");
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButtonReiniciar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButtonMezclar)))
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButtonInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jButtonInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMezclar)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonReiniciar)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReiniciarActionPerformed
        jTextFieldPrimerNombre.setText("");
        jTextFieldSegundoNombre.setText("");
        jLabelResultado.setText("");

        jTextFieldPrimerNombre.setEnabled(true);
        jTextFieldSegundoNombre.setEnabled(true);

        jButtonMezclar.setEnabled(true);
        
        jButtonReiniciar.setEnabled(false);
    }//GEN-LAST:event_jButtonReiniciarActionPerformed

    private void jButtonMezclarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMezclarActionPerformed

        String nombre1 = jTextFieldPrimerNombre.getText();
        String nombre2 = jTextFieldSegundoNombre.getText();

        jTextFieldPrimerNombre.setEnabled(false);
        jTextFieldSegundoNombre.setEnabled(false);

        jButtonReiniciar.setEnabled(true);
        jButtonMezclar.setEnabled(false);

        String[] nombres = mezclarNombres(nombre1, nombre2);
        String resultado = String.join(" - ", nombres);

        jLabelResultado.setText(resultado);
    }//GEN-LAST:event_jButtonMezclarActionPerformed

    public String[] mezclarNombres(String nombre1, String nombre2){
        String parte1 = nombre1.substring(0, nombre1.length() / 2);
        String parte2 = nombre2.substring(0, nombre2.length() / 2);
        
        String nombreMix1 = parte1 + parte2;
        String nombreMix2 = parte2 + parte1;
        String nombreMix3 = nombre1.substring(nombre1.length() / 2) + nombre2.substring(0, nombre2.length() / 2);
        String nombreMix4 = nombre2.substring(nombre2.length() / 2) + nombre1.substring(0, nombre1.length() / 2);
       
        return new String[]{nombreMix1.toUpperCase(), nombreMix2.toUpperCase(), nombreMix3.toUpperCase(), nombreMix4.toUpperCase()};
    }
    
    
    
    
    
    
    private void jTextFieldPrimerNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrimerNombreActionPerformed
    }//GEN-LAST:event_jTextFieldPrimerNombreActionPerformed

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonInicioActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JButton jButtonMezclar;
    private javax.swing.JButton jButtonReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JTextField jTextFieldPrimerNombre;
    private javax.swing.JTextField jTextFieldSegundoNombre;
    // End of variables declaration//GEN-END:variables
}
