/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jcmexamennb;

import java.awt.Color;
import java.awt.Image;
import java.util.TimerTask;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Jh0ny2k2
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        jPanelColoresJCM.setVisible(false);
        jPanelConcesionario.setVisible(false);
        jPanelListaJCM.setVisible(false);
        jPanelMainJCM.setVisible(true);
        
        jButtonEjercicio1JCM.setToolTipText("Ejercicio 1");
        jButtonEjercicio2JCM.setToolTipText("Ejercicio 2");
        jButtonEjercicio3JCM.setToolTipText("Ejercicio 3");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoConcesionarioJCM = new javax.swing.ButtonGroup();
        buttonGroupColorConcesionarioJCM = new javax.swing.ButtonGroup();
        jPanelInicioJCM = new javax.swing.JPanel();
        jPanelColoresJCM = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButtonFondoJCM = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelCambioColoresJCM = new javax.swing.JLabel();
        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel6 = new javax.swing.JPanel();
        jLabelAplicacion4 = new javax.swing.JLabel();
        jPanelListaJCM = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldColorListaJCM = new javax.swing.JTextField();
        jLabelEleccionListaJCM = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListColoresJCM = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jButtonAddColorJCM = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelAplicacion3 = new javax.swing.JLabel();
        jPanelConcesionario = new javax.swing.JPanel();
        jRadioButtonGasolinaJCM = new javax.swing.JRadioButton();
        jRadioButtonDieselJCM = new javax.swing.JRadioButton();
        jRadioButtonElectricoJCM = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonVerdeJCM = new javax.swing.JRadioButton();
        jRadioButtonRojoJCM = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonAzulConcesionario = new javax.swing.JRadioButton();
        jLabelResultadoTipoJCM = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelResultadoColorJCM1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelAplicacion2 = new javax.swing.JLabel();
        jPanelTimer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelAplicacion1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanelMainJCM = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelAplicacion = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonEjercicio1JCM = new javax.swing.JButton();
        jButtonEjercicio2JCM = new javax.swing.JButton();
        jButtonEjercicio3JCM = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemEjercicio1JCM = new javax.swing.JMenuItem();
        jMenuItemEjercicio2JCM = new javax.swing.JMenuItem();
        jMenuItemEjercicio3JCM = new javax.swing.JMenuItem();
        jMenuItemEjercicio4JCM = new javax.swing.JMenuItem();
        jMenuIndo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelInicioJCM.setLayout(new java.awt.CardLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("CAMBIADOR DE COLORES");

        jButtonFondoJCM.setText("Cambiar Fondo");
        jButtonFondoJCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFondoJCMActionPerformed(evt);
            }
        });

        jButton1.setText("Cambiar Letra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelCambioColoresJCM.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelCambioColoresJCM.setText("Label de ejemplo");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelAplicacion4.setText("Ejercicio 3");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAplicacion4, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(526, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAplicacion4, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelColoresJCMLayout = new javax.swing.GroupLayout(jPanelColoresJCM);
        jPanelColoresJCM.setLayout(jPanelColoresJCMLayout);
        jPanelColoresJCMLayout.setHorizontalGroup(
            jPanelColoresJCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColoresJCMLayout.createSequentialGroup()
                .addGroup(jPanelColoresJCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelColoresJCMLayout.createSequentialGroup()
                        .addGroup(jPanelColoresJCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelColoresJCMLayout.createSequentialGroup()
                                .addGap(313, 313, 313)
                                .addComponent(jButtonFondoJCM)
                                .addGap(184, 184, 184)
                                .addComponent(jButton1))
                            .addGroup(jPanelColoresJCMLayout.createSequentialGroup()
                                .addGap(420, 420, 420)
                                .addComponent(jLabelCambioColoresJCM))
                            .addGroup(jPanelColoresJCMLayout.createSequentialGroup()
                                .addGap(386, 386, 386)
                                .addComponent(jLabel8))
                            .addGroup(jPanelColoresJCMLayout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelColoresJCMLayout.setVerticalGroup(
            jPanelColoresJCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColoresJCMLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(32, 32, 32)
                .addComponent(jLabelCambioColoresJCM)
                .addGap(37, 37, 37)
                .addGroup(jPanelColoresJCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonFondoJCM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelInicioJCM.add(jPanelColoresJCM, "card2");

        jLabel5.setText("Añadir Color a Lista");

        jListColoresJCM.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListColoresJCM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListColoresJCMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListColoresJCM);

        jLabel6.setText("Lista de colores");

        jButtonAddColorJCM.setText("jButton1");
        jButtonAddColorJCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddColorJCMActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel7.setText("AÑADIR COLOR A LISTA");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelAplicacion3.setText("Ejercicio 2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAplicacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(526, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAplicacion3, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelListaJCMLayout = new javax.swing.GroupLayout(jPanelListaJCM);
        jPanelListaJCM.setLayout(jPanelListaJCMLayout);
        jPanelListaJCMLayout.setHorizontalGroup(
            jPanelListaJCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaJCMLayout.createSequentialGroup()
                .addGroup(jPanelListaJCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListaJCMLayout.createSequentialGroup()
                        .addGroup(jPanelListaJCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelListaJCMLayout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(jPanelListaJCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanelListaJCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelListaJCMLayout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(28, 28, 28)
                                            .addComponent(jTextFieldColorListaJCM, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelListaJCMLayout.createSequentialGroup()
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(243, 243, 243)
                                            .addComponent(jLabelEleccionListaJCM, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(13, 13, 13)))
                                    .addGroup(jPanelListaJCMLayout.createSequentialGroup()
                                        .addGap(377, 377, 377)
                                        .addComponent(jButtonAddColorJCM))))
                            .addGroup(jPanelListaJCMLayout.createSequentialGroup()
                                .addGap(374, 374, 374)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelListaJCMLayout.setVerticalGroup(
            jPanelListaJCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaJCMLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel7)
                .addGap(69, 69, 69)
                .addGroup(jPanelListaJCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldColorListaJCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelListaJCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListaJCMLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAddColorJCM)
                        .addGap(129, 129, 129)
                        .addComponent(jLabelEleccionListaJCM, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelListaJCMLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelInicioJCM.add(jPanelListaJCM, "card3");

        buttonGroupTipoConcesionarioJCM.add(jRadioButtonGasolinaJCM);
        jRadioButtonGasolinaJCM.setText("Gasolina");
        jRadioButtonGasolinaJCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGasolinaJCMActionPerformed(evt);
            }
        });

        buttonGroupTipoConcesionarioJCM.add(jRadioButtonDieselJCM);
        jRadioButtonDieselJCM.setText("Diesel");
        jRadioButtonDieselJCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDieselJCMActionPerformed(evt);
            }
        });

        buttonGroupTipoConcesionarioJCM.add(jRadioButtonElectricoJCM);
        jRadioButtonElectricoJCM.setText("Electrico");
        jRadioButtonElectricoJCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonElectricoJCMActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo");

        buttonGroupColorConcesionarioJCM.add(jRadioButtonVerdeJCM);
        jRadioButtonVerdeJCM.setText("Verde");
        jRadioButtonVerdeJCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVerdeJCMActionPerformed(evt);
            }
        });

        buttonGroupColorConcesionarioJCM.add(jRadioButtonRojoJCM);
        jRadioButtonRojoJCM.setText("Rojo");
        jRadioButtonRojoJCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRojoJCMActionPerformed(evt);
            }
        });

        jLabel1.setText("Color");

        buttonGroupColorConcesionarioJCM.add(jRadioButtonAzulConcesionario);
        jRadioButtonAzulConcesionario.setText("Azul");
        jRadioButtonAzulConcesionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAzulConcesionarioActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setText("CONCESIONARIO");

        jLabel3.setText("Has elegido un coche:");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelAplicacion2.setText("Ejercicio 1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAplicacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(532, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAplicacion2, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelConcesionarioLayout = new javax.swing.GroupLayout(jPanelConcesionario);
        jPanelConcesionario.setLayout(jPanelConcesionarioLayout);
        jPanelConcesionarioLayout.setHorizontalGroup(
            jPanelConcesionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConcesionarioLayout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelConcesionarioLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(jPanelConcesionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConcesionarioLayout.createSequentialGroup()
                        .addGroup(jPanelConcesionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jRadioButtonElectricoJCM)
                            .addComponent(jRadioButtonDieselJCM)
                            .addComponent(jRadioButtonGasolinaJCM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelConcesionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanelConcesionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonVerdeJCM, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jRadioButtonRojoJCM))
                            .addComponent(jRadioButtonAzulConcesionario))
                        .addGap(218, 218, 218))
                    .addGroup(jPanelConcesionarioLayout.createSequentialGroup()
                        .addGroup(jPanelConcesionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelResultadoTipoJCM, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelConcesionarioLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(31, 31, 31)
                                .addComponent(jLabelResultadoColorJCM1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelConcesionarioLayout.setVerticalGroup(
            jPanelConcesionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConcesionarioLayout.createSequentialGroup()
                .addGroup(jPanelConcesionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConcesionarioLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel4)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonVerdeJCM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonRojoJCM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonAzulConcesionario))
                    .addGroup(jPanelConcesionarioLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonGasolinaJCM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonDieselJCM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonElectricoJCM)))
                .addGap(23, 23, 23)
                .addGroup(jPanelConcesionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabelResultadoColorJCM1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelResultadoTipoJCM, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelInicioJCM.add(jPanelConcesionario, "card4");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelAplicacion1.setText("Ejercicio4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAplicacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(532, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAplicacion1, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelTimerLayout = new javax.swing.GroupLayout(jPanelTimer);
        jPanelTimer.setLayout(jPanelTimerLayout);
        jPanelTimerLayout.setHorizontalGroup(
            jPanelTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelTimerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTimerLayout.setVerticalGroup(
            jPanelTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTimerLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelInicioJCM.add(jPanelTimer, "card5");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelAplicacion.setText("PANTALLA MAIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(532, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        jButtonEjercicio1JCM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jcmexamennb/Images/uno.png"))); // NOI18N
        jButtonEjercicio1JCM.setIconTextGap(0);
        jButtonEjercicio1JCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjercicio1JCMActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonEjercicio1JCM);

        jButtonEjercicio2JCM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jcmexamennb/Images/dos.png"))); // NOI18N
        jButtonEjercicio2JCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjercicio2JCMActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonEjercicio2JCM);

        jButtonEjercicio3JCM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jcmexamennb/Images/tres.png"))); // NOI18N
        jButtonEjercicio3JCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjercicio3JCMActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonEjercicio3JCM);

        javax.swing.GroupLayout jPanelMainJCMLayout = new javax.swing.GroupLayout(jPanelMainJCM);
        jPanelMainJCM.setLayout(jPanelMainJCMLayout);
        jPanelMainJCMLayout.setHorizontalGroup(
            jPanelMainJCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelMainJCMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMainJCMLayout.setVerticalGroup(
            jPanelMainJCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainJCMLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 577, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelInicioJCM.add(jPanelMainJCM, "card5");

        getContentPane().add(jPanelInicioJCM, java.awt.BorderLayout.CENTER);

        jMenu4.setText("Ejercicios");

        jMenuItemEjercicio1JCM.setText("Ejercicio1");
        jMenuItemEjercicio1JCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEjercicio1JCMActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemEjercicio1JCM);

        jMenuItemEjercicio2JCM.setText("Ejercicio2");
        jMenuItemEjercicio2JCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEjercicio2JCMActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemEjercicio2JCM);

        jMenuItemEjercicio3JCM.setText("Ejercicio3");
        jMenuItemEjercicio3JCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEjercicio3JCMActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemEjercicio3JCM);

        jMenuItemEjercicio4JCM.setText("Ejercicio4");
        jMenuItemEjercicio4JCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEjercicio4JCMActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemEjercicio4JCM);

        jMenuBar2.add(jMenu4);

        jMenuIndo.setText("Info");
        jMenuIndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIndoActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Informacion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuIndo.add(jMenuItem1);

        jMenuBar2.add(jMenuIndo);

        jMenu1.setText("Salir");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSalir);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemEjercicio3JCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEjercicio3JCMActionPerformed
        if (jPanelMainJCM.isVisible()) {
            jPanelMainJCM.setVisible(false);
            jPanelColoresJCM.setVisible(true);
        } else  if (jPanelConcesionario.isVisible()) {
            jPanelConcesionario.setVisible(false);
            jPanelColoresJCM.setVisible(true);
        } else if (jPanelListaJCM.isVisible()) {
            jPanelListaJCM.setVisible(false);
            jPanelColoresJCM.setVisible(true);
        } else if (jPanelTimer.isVisible()) {
            jPanelTimer.setVisible(false);
            jPanelColoresJCM.setVisible(true);
        }   
    }//GEN-LAST:event_jMenuItemEjercicio3JCMActionPerformed

    private void jMenuItemEjercicio1JCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEjercicio1JCMActionPerformed
        if (jPanelMainJCM.isVisible()) {
            jPanelMainJCM.setVisible(false);
            jPanelConcesionario.setVisible(true);
        } else if (jPanelListaJCM.isVisible()) {
            jPanelListaJCM.setVisible(false);
            jPanelConcesionario.setVisible(true);
        } else if (jPanelColoresJCM.isVisible()) {
            jPanelColoresJCM.setVisible(false);
            jPanelConcesionario.setVisible(true);
        } else if (jPanelTimer.isVisible()) {
            jPanelTimer.setVisible(false);
            jPanelConcesionario.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemEjercicio1JCMActionPerformed

    private void jRadioButtonGasolinaJCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGasolinaJCMActionPerformed
        String texto = "Tipo: Gasolina";
        
        jLabelResultadoTipoJCM.setText(texto);
    }//GEN-LAST:event_jRadioButtonGasolinaJCMActionPerformed

    private void jRadioButtonDieselJCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDieselJCMActionPerformed
        String texto = "Tipo: Diesel";
        
        jLabelResultadoTipoJCM.setText(texto);
    }//GEN-LAST:event_jRadioButtonDieselJCMActionPerformed

    private void jRadioButtonElectricoJCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonElectricoJCMActionPerformed
        String texto = "Tipo: Electrico";
        
        jLabelResultadoTipoJCM.setText(texto);
    }//GEN-LAST:event_jRadioButtonElectricoJCMActionPerformed

    private void jRadioButtonVerdeJCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVerdeJCMActionPerformed
        String texto = "Color: Verde";
        
        jLabelResultadoColorJCM1.setText(texto);
    }//GEN-LAST:event_jRadioButtonVerdeJCMActionPerformed

    private void jRadioButtonRojoJCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRojoJCMActionPerformed
        String texto = "Color: Rojo";
        
        jLabelResultadoColorJCM1.setText(texto);
    }//GEN-LAST:event_jRadioButtonRojoJCMActionPerformed

    private void jRadioButtonAzulConcesionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAzulConcesionarioActionPerformed
        String texto = "Color: Azul";
        
        jLabelResultadoColorJCM1.setText(texto);
    }//GEN-LAST:event_jRadioButtonAzulConcesionarioActionPerformed

    private void jMenuItemEjercicio2JCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEjercicio2JCMActionPerformed
        if (jPanelMainJCM.isVisible()) {
            jPanelMainJCM.setVisible(false);
            jPanelListaJCM.setVisible(true);
        } else if (jPanelConcesionario.isVisible()) {
            jPanelConcesionario.setVisible(false);
            jPanelListaJCM.setVisible(true);
        } else if (jPanelColoresJCM.isVisible()) {
            jPanelColoresJCM.setVisible(false);
            jPanelListaJCM.setVisible(true);
        } else if (jPanelTimer.isVisible()) {
            jPanelTimer.setVisible(false);
            jPanelListaJCM.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemEjercicio2JCMActionPerformed

    private void jButtonAddColorJCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddColorJCMActionPerformed
        String color = jTextFieldColorListaJCM.getText().trim();
       
        DefaultListModel<String> modeloListaColoresJCM = new DefaultListModel<>();
        jListColoresJCM.setModel(modeloListaColoresJCM);
        
        modeloListaColoresJCM.addElement(color);
    }//GEN-LAST:event_jButtonAddColorJCMActionPerformed

    private void jListColoresJCMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListColoresJCMMouseClicked
        String color = jListColoresJCM.getSelectedValue().toString();
        
        jLabelEleccionListaJCM.setText(color);
    }//GEN-LAST:event_jListColoresJCMMouseClicked

    private void jButtonFondoJCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFondoJCMActionPerformed
        Color color = jColorChooser1.getColor(); 
        
        jPanelColoresJCM.setBackground(color);
    }//GEN-LAST:event_jButtonFondoJCMActionPerformed

    private void jMenuItemEjercicio4JCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEjercicio4JCMActionPerformed
        if (jPanelMainJCM.isVisible()) {
            jPanelMainJCM.setVisible(false);
            jPanelTimer.setVisible(true);
        } else  if (jPanelConcesionario.isVisible()) {
            jPanelConcesionario.setVisible(false);
            jPanelTimer.setVisible(true);
        } else if (jPanelListaJCM.isVisible()) {
            jPanelListaJCM.setVisible(false);
            jPanelTimer.setVisible(true);
        } else if (jPanelColoresJCM.isVisible()) {
            jPanelColoresJCM.setVisible(false);
            jPanelTimer.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemEjercicio4JCMActionPerformed

    private void jMenuIndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIndoActionPerformed
        
    }//GEN-LAST:event_jMenuIndoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        InfoConce info = new InfoConce(this, true);
        
        info.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Color color = jColorChooser1.getColor(); 
        
        jLabelCambioColoresJCM.setForeground(color);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de que quieres salir?",
                "Confirmación de Salida",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0); // Salir de la aplicación
        }
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jButtonEjercicio2JCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjercicio2JCMActionPerformed
        
        
        if (jPanelMainJCM.isVisible()) {
            jPanelMainJCM.setVisible(false);
            jPanelListaJCM.setVisible(true);
        } else if (jPanelConcesionario.isVisible()) {
            jPanelConcesionario.setVisible(false);
            jPanelListaJCM.setVisible(true);
        } else if (jPanelColoresJCM.isVisible()) {
            jPanelColoresJCM.setVisible(false);
            jPanelListaJCM.setVisible(true);
        } else if (jPanelTimer.isVisible()) {
            jPanelTimer.setVisible(false);
            jPanelListaJCM.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEjercicio2JCMActionPerformed

    private void jButtonEjercicio3JCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjercicio3JCMActionPerformed
        if (jPanelMainJCM.isVisible()) {
            jPanelMainJCM.setVisible(false);
            jPanelColoresJCM.setVisible(true);
        } else  if (jPanelConcesionario.isVisible()) {
            jPanelConcesionario.setVisible(false);
            jPanelColoresJCM.setVisible(true);
        } else if (jPanelListaJCM.isVisible()) {
            jPanelListaJCM.setVisible(false);
            jPanelColoresJCM.setVisible(true);
        } else if (jPanelTimer.isVisible()) {
            jPanelTimer.setVisible(false);
            jPanelColoresJCM.setVisible(true);
        }  
    }//GEN-LAST:event_jButtonEjercicio3JCMActionPerformed

    private void jButtonEjercicio1JCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjercicio1JCMActionPerformed
        if (jPanelMainJCM.isVisible()) {
            jPanelMainJCM.setVisible(false);
            jPanelConcesionario.setVisible(true);
        } else if (jPanelListaJCM.isVisible()) {
            jPanelListaJCM.setVisible(false);
            jPanelConcesionario.setVisible(true);
        } else if (jPanelColoresJCM.isVisible()) {
            jPanelColoresJCM.setVisible(false);
            jPanelConcesionario.setVisible(true);
        } else if (jPanelTimer.isVisible()) {
            jPanelTimer.setVisible(false);
            jPanelConcesionario.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEjercicio1JCMActionPerformed

    private void cambiarImagen() {

        
        
        
        
        
        
        
    
    } 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupColorConcesionarioJCM;
    private javax.swing.ButtonGroup buttonGroupTipoConcesionarioJCM;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddColorJCM;
    private javax.swing.JButton jButtonEjercicio1JCM;
    private javax.swing.JButton jButtonEjercicio2JCM;
    private javax.swing.JButton jButtonEjercicio3JCM;
    private javax.swing.JButton jButtonFondoJCM;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAplicacion;
    private javax.swing.JLabel jLabelAplicacion1;
    private javax.swing.JLabel jLabelAplicacion2;
    private javax.swing.JLabel jLabelAplicacion3;
    private javax.swing.JLabel jLabelAplicacion4;
    private javax.swing.JLabel jLabelCambioColoresJCM;
    private javax.swing.JLabel jLabelEleccionListaJCM;
    private javax.swing.JLabel jLabelResultadoColorJCM1;
    private javax.swing.JLabel jLabelResultadoTipoJCM;
    private javax.swing.JList<String> jListColoresJCM;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuIndo;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemEjercicio1JCM;
    private javax.swing.JMenuItem jMenuItemEjercicio2JCM;
    private javax.swing.JMenuItem jMenuItemEjercicio3JCM;
    private javax.swing.JMenuItem jMenuItemEjercicio4JCM;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelColoresJCM;
    private javax.swing.JPanel jPanelConcesionario;
    private javax.swing.JPanel jPanelInicioJCM;
    private javax.swing.JPanel jPanelListaJCM;
    private javax.swing.JPanel jPanelMainJCM;
    private javax.swing.JPanel jPanelTimer;
    private javax.swing.JRadioButton jRadioButtonAzulConcesionario;
    private javax.swing.JRadioButton jRadioButtonDieselJCM;
    private javax.swing.JRadioButton jRadioButtonElectricoJCM;
    private javax.swing.JRadioButton jRadioButtonGasolinaJCM;
    private javax.swing.JRadioButton jRadioButtonRojoJCM;
    private javax.swing.JRadioButton jRadioButtonVerdeJCM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldColorListaJCM;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
